export const AdminAsyncStateConstants = {
    branches: 'branches',
    roles: 'roles',
    members: 'members',
    units: 'units',
    groups: 'groups',
    customers: 'customers',
    suppliers: 'suppliers',
    expensesDestinations: 'expensesDestinations',
    paymentMethods: 'paymentMethods',
    taxes: 'taxes',
    tables: 'tables',
    expenses: 'expenses',
    delivery: 'delivery',
    additions: 'additions',
    products: 'products',
    comboOffers: 'comboOffers',
    discounts: 'discounts',
}