export const FireStoreCollectionsConstants = {
    USERS: 'users',
    USERS_PRIVATE_DATA: 'users_private_data',
    REQUEST_TRAIL: 'request_trail',
    BRANCHES: 'branches',
    PRODUCTS: 'products',
    UNITS: 'units',
    CATEGORIES: 'categories',
    MEMBERS: 'members',
    ROLES: 'roles',
    TAXES: 'taxes',
    GROUPS: 'groups',
    CUSTOMERS: 'customers',
    EXPENSES_DEST: 'expensesDest',
    TABLES: 'tables',
}