export const FireStoreCollectionsConstants = {
    USERS: 'users',
    USERS_PRIVATE_DATA: 'users_private_data',
    REQUEST_TRAIL: 'request_trail',
    BRANCHES: 'branches',
    PRODUCTS: 'products',
    UNITS: 'units',
    CATEGORIES: 'categories',
    MEMBERS: 'members',
    ROLES: 'roles',
    TAXES: 'taxes',
    GROUPS: 'groups',
    CUSTOMERS: 'customers',
    SUPPLIERS: 'suppliers',
    EXPENSES_DESTINATIONS: 'expenses_destinations',
    PAYMENTS_METHODS: 'payments_methods',
    TABLES: 'tables',
    EXPENSES: 'expenses',
    DELIVERY: 'delivery',
    ADDITIONS: 'additions',
    COMBO_OFFERS: 'combo_offers',
    DISCOUNTS: 'discounts',
}