export const TRANSLATE = {
    LOGIN: 'login',
    REGISTER: 'register',
    MOBILE: 'mobile',
    PASSWORD: 'password',
    FORGOT_PASSWORD: 'forgotPassword',
    DONT_HAVE_ACCOUNT: 'dontHaveAccount',
    THIS_FIELD_IS_REQUIRED: 'thisFieldIsRequired',
    NAME: 'name',
    ALREADY_HAVE_ACCOUNT: 'alreadyHaveAccount',
    SEND_OTP: 'sendOTP',
    WE_WILL_SEND_OTP: 'weWillSendOTP',
    OTP_VERIFICATION: 'otpVerification',
    WE_HAVE_SENT_OTP: 'weHaveSentOTP',
    VERIFY: 'verify',
    INVALID_OTP: 'invalidOTP',
    APP_NAME: 'appName',
    DASHBOARD: 'dashboard',
}
